### PR TITLE
avoids spawning of timeout thread if no timeout set

### LINKED ISSUE #253: simulation timeout thread is started unconditionally, leading to unnecessary overhead
We realized that for very short (few seconds) simulations, there is considerable overhead:

```console
$ time strace -c -f -p 5634
...
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 65.13    0.006429           2      2997       699 futex
 32.42    0.003200          33        96           madvise
  1.62    0.000160           1        96           clone
  0.83    0.000082           0        96           set_robust_list
  0.00    0.000000           0         2           write
------ ----------- ----------- --------- --------- ----------------
100.00    0.009871                  3287       699 total

real    0m3.984s
user    0m0.027s
sys    0m0.070s
```

There's a lot going on in thread creation (clone) and coordination (futex) that is not necessary, especially not for a single-core run. This is due to `def simulate` in `spotpy/algorithms/_algorithm.py`. 

My proposal is to only spawn the thread if `self.sim_timeout` is set to avoid the above-mentioned overhead. I'll prepare a pull request.

### PR DESCRIPTION
**Pull request by wookietreiber**
fixes #253

### CODE REVIEW

**Comment by wookietreiber** [comment]
@thouska What are your recommendations regarding the coverage diff?

**Comment by thouska** [comment]
Great thank you! 
As the issue is arrising with single-core usage, how about checking for that with
`if not parallel == 'seq':` 
instaead of 
`if self.sim_timeout:`?

**Comment by wookietreiber** [comment]
@thouska The overhead is not just with single-core usage. Generally, if you don't have/need/want a timeout, you should not need to pay the overhead cost of the extra thread and the logistics around it.

**Comment by thouska** [comment]
Ok, you are right, than we leave it like that and check for the timeout.  And never mind the coverage, it varies from time to time because i have’nt set a random seed. Therefor some algorithms behave differently from one test to the other.
Your contribution will be available on pypi in spotpy version >=1.5.11 (propably published today, if not tomorrow).

**Comment by wookietreiber** [comment]
Alright, thanks for the quick response!

**Pull request merged**
