### PR TITLE
Feature logging

### PR DESCRIPTION
**Pull request by cpwnd**
Hey I followed your discussion in #239 and went ahead to implement the standard logging library.
If you wan't to use the code, I'm happy to contribute.

#### What is already done

All print calls are replaced with a `logging.info` call. I don't know if the info level is always appropriate.
I changed your logging code in analyser.py (EDIT i mean objectivefunctions.py) to use the new main logger.
There is one print call in the database package. I don't know if its really necessary.

#### What has to be done

* **Add cli option and standard behavior**: Before merging there should be a defined standard behavior for the logging output. And also add a flag `--verbose/debug/quiet` or something like that, to toggle the standard behavior.
So we can met the requirements of the issue.
I wasn't quite sure how to add a new cli option that.
If you point me to the right direction I can add code for e.g. (1) `--quiet` => no console output/everything is printed to the file (2) default (no option) => info level and (3) `--debug` which then prints all `.debug(...)` messages as well.
Also printing to the file can be disabled too.
* **Logging format**: Also an question for me is: We can change the current format of the logging messages, whether the current format suits your needs. Is the current format ok with you:

https://github.com/cpwnd/spotpy/blob/15e219692f6d7d8a9553264a5830a92b481cde82/spotpy/spotpylogging.py#L16

#### Not implemented in this pr
In my opinion would be possible next steps, that can be adressed with future pull requests:
  1. The logging messages are now all at level info. They can be more nuanced, to have different outputs for different use cases. E.g. the individuals steps of an algorithm can be on the debug level. (optional) @thouska remove/change logging calls with \n they prevent a nice reading flow (just my opinion) 
  2. At the moment, the standard file name for the logging output is spotpy.log. This is used for subsequent calls and every run is appended in this file. Of course this can be changed, maybe with a /log directory and a timestamp-suffixed filename.
  3. Maybe you want to be able to use a file config, e.g. to control the log level or the output file. see https://docs.python.org/3/howto/logging.html#configuring-logging

At the moment I tested only with different tutorials from the examples folder.

Hope to hear from you soon :)

### CODE REVIEW

**Comment by thouska** [comment]
Hi @cpwnd ,
super nice, thank you for this cool contribution! I tested it and it runs smothely on my PC.

Three minor things: 
- I get every logging message twice in my console, however, the spotpy.log file has only one entry for each message
- The path for the logfile should be possible to set (I assume this can/will be done when working on the cli option).
- In my opinion, [the time stamp](https://github.com/cpwnd/spotpy/blob/15e219692f6d7d8a9553264a5830a92b481cde82/spotpy/spotpylogging.py#L16) is not necessary.

I will work on you PR and implement different levels of the logging. Indeed some of the stuff from the algorithms can be seen as --debug

@philippkraft what do you think about the cli option, logging format and having a logging file?

**Comment by cpwnd** [comment]
Hey, you can now set logfile, logdir and verbosity as "quiet" via cli parameters. I tested it via your suggested way:

```python
from spotpy.cli import main
from spotpy.examples.spot_setup_rosenbrock import spot_setup

setup = spot_setup()
main(setup)
```

And then start it via command line e.g. `$ python script.py --logfile test.log --quiet`

> The path for the logfile should be possible to set (I assume this can/will be done when working on the cli option).

I think we  implemented now all remaining points.

**Comment by cpwnd** [comment]
Is this line important? Thats the last print statement remaining.
https://github.com/thouska/spotpy/blob/6be2dcfa17e34e65dd43bf9f369da39c597d5760/spotpy/database/__init__.py#L21

Maybe it can be replaced by the logger. If yes, then the `database/__init__` also needs a logger object.

**Comment by cpwnd** [comment]
With the last two commits, at least for me, this is finished. Can be merged into master now.

**Comment by thouska** [comment]
Hi @cpwnd,

thx for pushing this new feature. I tested it on my device and it works almost perfect. However, there is one strange error:
Everytime it is started for the frst time in an interactive console, any of the example errors with:

> Traceback (most recent call last):
>   File "...\spotpy\examples\tutorial_parallel_computing_hymod.py", line 44, in <module>
>   sampler=spotpy.algorithms.mc(spot_setup, dbname='Parallel_hymod', dbformat='csv',
>   File "...\spotpy\algorithms\mc.py", line 53, in __init__
 >    super(mc, self).__init__(*args, **kwargs)
>   File "...\spotpy\algorithms\_algorithm.py", line 221, in __init__
>    self.logger = spotpylogging.instantiate_logger(self.__class__.__name__, quiet, logfile, logdir)
>  File "...\spotpy\spotpylogging.py", line 49, in instantiate_logger
>  handler_file = logging.FileHandler(path_to_logfile)
>  File "...\anaconda3\lib\logging\__init__.py", line 1143, in __init__
>     StreamHandler.__init__(self, self._open())
>  File "...\anaconda3\lib\logging\__init__.py", line 1172, in _open
>     return open(self.baseFilename, self.mode, encoding=self.encoding)

> OSError: [Errno 22] Invalid argument: '...\spotpy\examples\2021-06-15-spotpy.log'`

If I restated the code from there, it works without any error. Do you have any idea what could cause that behavior?

**Comment by cpwnd** [comment]
I don't have an anaconda installation at the moment. But when I start it
in an interactive console (ipython) it works. Also I'm using Ubuntu
instead of Windows.

How do you start the scripts in anaconda?

Am 15.06.21 um 16:07 schrieb thouska:

**Comment by thouska** [comment]
I start the scripts in Anaconda's spyder editor. 
I will try, how it works outside of spyer and keep you posted.

**Comment by cpwnd** [comment]
@thouska please check the branch again for your Windwos Anaconda setup. I replaced the logging paths now with `pathlib.PurePath`s, which are OS agnostic and should work everywhere.

**Comment by cpwnd** [comment]
Closing this in favor of #293

**Pull request closed without merging**
