### PR TITLE
Abc fscabc

### PR DESCRIPTION
**Pull request by p-lauer**
I added an implementation of ABC by Karaboga and FSCABC by Zhang.

### CODE REVIEW

**Comment by thouska** [comment]
This is a very powerful extension for SPOTPY! Thank you for this great piece of work and for your time you spend on this. Your code works fine on my computer and the layout fits perfecty to the other algorithms.

**Comment by p-lauer** [comment]
Good to hear. Also it works quite good parallelized with MPI, altough there is potential for performance improvement with the so called "scout bee phase", which I'm currently working on.

Did you have worked out some kind of verification and validation routine for the other algorithms, that could be applied here to? It seems that, at least on my problems, the implementation especially of FSCABC has a good performance, but some kind of evaluation would be a good idea, I think.

**Comment by thouska** [comment]
Thats great that you also thought about the parallelization. I have not tested this yet, but it looks like the parts where you have implemented it, should work fine.

I have included the abc and fscabc algorithms into the numerical optimization problems rosenbrock/griewank/ackley. I think the rosenbrock tutorial file is already updated on github. Maybe this helps. From what i can see so far is that both of your algorithms are robust to find the different global optima. Somerwhere in the range of Simulated Annealing. However, this is more a general guidance and no real verification. I guess this is only possible by comparing the results with the original code.
 
I found this `eb` parameter quiete sensitive to find a good solution in reasonable number of repetitions. Is there any rule of thumb for a good setting for a given number of parameters?

**Comment by p-lauer** [comment]
Based on my experience and literature, a good starting point for the population (2 `eb`)  is 50...500, while `a`, some kind of mutation factor - in literature is mostly stated as 1 - I think 0.1...1 would be something to start with. `limit` should be 1/2...2 `eb`. For `kpow` of FSCABC you could start maybe with 5...10.

**Pull request merged**
